// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Storage.Context;

#nullable disable

namespace Shop.Storage.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20251119092408_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Storage.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LastName");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Customer", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikola@gmail.com",
                            FirstName = "Nikola",
                            LastName = "Nikolic",
                            Uid = new Guid("03cd14e0-0fcf-40d5-8c09-14f045f2199c")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "stefan@gmail.com",
                            FirstName = "Stefan",
                            LastName = "Stefanovic",
                            Uid = new Guid("7234d4a4-eb61-43a0-ada7-061f3aa7b482")
                        });
                });

            modelBuilder.Entity("Shop.Storage.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerFk");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Status = 1,
                            Uid = new Guid("041b7c64-cda8-443d-abe2-623db850789b")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Status = 0,
                            Uid = new Guid("8906e152-40e2-4f3c-8a16-1232d9fcceb7")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Status = 0,
                            Uid = new Guid("c0177445-a2e6-4883-a378-7d227edc7758")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Status = 2,
                            Uid = new Guid("d8e2fcaa-c774-47ab-8f27-c526aa9a7a6c")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            DeletedOn = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Uid = new Guid("513c1ca0-6c62-4126-8d76-58ba231f5412")
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Status = 0,
                            Uid = new Guid("87a85d45-9aa8-405e-9a16-c443819f14b0")
                        });
                });

            modelBuilder.Entity("Shop.Storage.OrderItem.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderFk");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Price");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductFk");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            Price = 499.99m,
                            ProductId = 1,
                            Quantity = 2,
                            Uid = new Guid("0a4ddebb-72b6-433a-aa6e-06a19f6fc9fb")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            Price = 999.99m,
                            ProductId = 2,
                            Quantity = 1,
                            Uid = new Guid("415d1c0d-304d-42e2-9aa0-0f582913238a")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            Price = 2999.99m,
                            ProductId = 3,
                            Quantity = 1,
                            Uid = new Guid("e5a4d129-6694-4d1b-a438-5000960c9e8e")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 399.99m,
                            ProductId = 1,
                            Quantity = 3,
                            Uid = new Guid("5a0c6f64-400d-4e76-a35c-caeebfbd8989")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 1499.99m,
                            ProductId = 2,
                            Quantity = 1,
                            Uid = new Guid("dc41cf2a-6baf-4f16-a418-6a480f268bae")
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 31049.99m,
                            ProductId = 4,
                            Quantity = 1,
                            Uid = new Guid("e4d4f16c-3374-4e08-911a-6a9240b1de3d")
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 4,
                            Price = 34999.99m,
                            ProductId = 4,
                            Quantity = 1,
                            Uid = new Guid("4007a55e-fff8-4f78-bedb-787da3475a23")
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 5,
                            Price = 34999.99m,
                            ProductId = 4,
                            Quantity = 2,
                            Uid = new Guid("27590886-b01a-4895-8e1e-f00567d0383c")
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 6,
                            Price = 3499.99m,
                            ProductId = 3,
                            Quantity = 1,
                            Uid = new Guid("899aa8ea-7e02-4e6a-ad79-86b24e962b76")
                        });
                });

            modelBuilder.Entity("Shop.Storage.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Price");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Product", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Knjiga",
                            Price = 499.99m,
                            Uid = new Guid("9a5dbacd-111d-44b4-ab30-2d8a48d8feb7")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lampa",
                            Price = 1499.99m,
                            Uid = new Guid("51ccb483-5d77-4aea-a0df-2bf42a1b122e")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Slusalice",
                            Price = 2999.99m,
                            Uid = new Guid("33f4c890-dd02-4843-9897-b55594ccd64d")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Telefon",
                            Price = 31049.99m,
                            Uid = new Guid("96044c8a-1bc7-4c40-80d4-f9a3de4eea9e")
                        });
                });

            modelBuilder.Entity("Shop.Storage.Order.Order", b =>
                {
                    b.HasOne("Shop.Storage.Customer.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Shop.Storage.OrderItem.OrderItem", b =>
                {
                    b.HasOne("Shop.Storage.Order.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Storage.Product.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Storage.Customer.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shop.Storage.Order.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Shop.Storage.Product.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
