// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Storage.Context;

#nullable disable

namespace Shop.Storage.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20251119124427_UpdatedSeedDataWithMoreProducts")]
    partial class UpdatedSeedDataWithMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Storage.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LastName");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Customer", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikola@gmail.com",
                            FirstName = "Nikola",
                            LastName = "Nikolic",
                            Uid = new Guid("b852a0d3-7051-4109-ba7a-850d483896d1")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "stefan@gmail.com",
                            FirstName = "Stefan",
                            LastName = "Stefanovic",
                            Uid = new Guid("411eb0e7-a369-48a1-b60e-542781126882")
                        });
                });

            modelBuilder.Entity("Shop.Storage.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerFk");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Status = 1,
                            Uid = new Guid("261230e5-4079-4abe-9bfd-df1a37c875ba")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Status = 0,
                            Uid = new Guid("15995e4c-dde8-4489-9e25-efac2cb553f9")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Status = 0,
                            Uid = new Guid("8efddfd5-734e-4d14-89a7-48c83661aee8")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Status = 2,
                            Uid = new Guid("292ae322-532d-426b-b765-9ea97a2b47e6")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            DeletedOn = new DateTime(2025, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Uid = new Guid("f7176ed9-924e-4f9b-8879-fa2b53aed3e5")
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Status = 0,
                            Uid = new Guid("7061f141-ed24-4b4c-af2f-cbce97e8aae9")
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Status = 1,
                            Uid = new Guid("1c0752cc-fb3c-4878-a13d-69b601f793c9")
                        });
                });

            modelBuilder.Entity("Shop.Storage.OrderItem.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderFk");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Price");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductFk");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            Price = 499.99m,
                            ProductId = 1,
                            Quantity = 2,
                            Uid = new Guid("bf8b66ac-c701-4117-b73c-3c231f1d73a0")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            Price = 999.99m,
                            ProductId = 2,
                            Quantity = 1,
                            Uid = new Guid("e5993fa1-4999-455b-8af9-c665340bc0c2")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            Price = 2999.99m,
                            ProductId = 3,
                            Quantity = 1,
                            Uid = new Guid("fff28a7f-d481-496d-96e0-917a1ef7f24d")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 399.99m,
                            ProductId = 1,
                            Quantity = 3,
                            Uid = new Guid("31e9d67e-f7c4-478b-b280-9a96da9e9804")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 1499.99m,
                            ProductId = 2,
                            Quantity = 1,
                            Uid = new Guid("657e62cf-dfdc-4daf-9075-a6f5053d4361")
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 31049.99m,
                            ProductId = 4,
                            Quantity = 1,
                            Uid = new Guid("7a369ae8-29fb-4e88-ac01-b00cebdd3a10")
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 4,
                            Price = 34999.99m,
                            ProductId = 4,
                            Quantity = 1,
                            Uid = new Guid("7e8be5e0-c1f2-44fc-b530-59d893407c31")
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 5,
                            Price = 34999.99m,
                            ProductId = 4,
                            Quantity = 2,
                            Uid = new Guid("e1fbf861-3d6b-4208-9730-e11a4d8a10b1")
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 6,
                            Price = 3499.99m,
                            ProductId = 3,
                            Quantity = 1,
                            Uid = new Guid("781abe5d-d197-409e-ae82-56b5b7d4d3ad")
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 6,
                            Price = 9999.99m,
                            ProductId = 5,
                            Quantity = 1,
                            Uid = new Guid("ba857fbe-fff0-48fb-bae8-81ab3dbdfd75")
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 6,
                            Price = 3499.99m,
                            ProductId = 6,
                            Quantity = 2,
                            Uid = new Guid("6a6eb388-4b2f-4ab8-8813-404212c55e55")
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 6,
                            Price = 1199.99m,
                            ProductId = 7,
                            Quantity = 4,
                            Uid = new Guid("85e10880-0b87-417d-a30e-fc66f18f8e1e")
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 7,
                            Price = 199.99m,
                            ProductId = 8,
                            Quantity = 4,
                            Uid = new Guid("c756a242-a91f-4fc9-8062-c557f165c1ab")
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 7,
                            Price = 8999.99m,
                            ProductId = 9,
                            Quantity = 1,
                            Uid = new Guid("27a2f51b-bd57-44af-8984-47d0f27ed8e4")
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 7,
                            Price = 12999.99m,
                            ProductId = 10,
                            Quantity = 1,
                            Uid = new Guid("c24fa34b-71f8-4a15-b344-c15af876a951")
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 7,
                            Price = 49999.99m,
                            ProductId = 11,
                            Quantity = 1,
                            Uid = new Guid("5e12c4d7-2e9a-4fd5-aec9-4ef7614f1f98")
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 7,
                            Price = 39999.99m,
                            ProductId = 12,
                            Quantity = 1,
                            Uid = new Guid("036440a5-2b83-4f41-96f8-7b7c85bb9d40")
                        });
                });

            modelBuilder.Entity("Shop.Storage.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("CreatedOn");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DeletedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Price");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Product", "Shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Knjiga",
                            Price = 499.99m,
                            Uid = new Guid("2b4ef0b3-8fe5-46f6-ad73-979b2036481d")
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lampa",
                            Price = 1499.99m,
                            Uid = new Guid("17b6e705-9dd0-44f8-a3a0-73865f93c3cc")
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Slusalice",
                            Price = 2999.99m,
                            Uid = new Guid("80f16508-4180-4498-81d6-a630bff4a4b5")
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Telefon",
                            Price = 31049.99m,
                            Uid = new Guid("01007967-7b47-47fc-9e3d-d54af30df201")
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Patike",
                            Price = 9999.99m,
                            Uid = new Guid("f94b3625-d49a-4ac4-baf3-5c554d35283f")
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pantalone",
                            Price = 4499.99m,
                            Uid = new Guid("3dfe09c1-e497-4833-94eb-ac171ad95e5a")
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Majica",
                            Price = 1199.99m,
                            Uid = new Guid("ffda6fd2-11a1-4cf0-8f35-195a813332b9")
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tanjir",
                            Price = 299.99m,
                            Uid = new Guid("ad1efbd0-c5a2-42ff-b129-156f3065d25c")
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jakna",
                            Price = 8999.99m,
                            Uid = new Guid("71bb50cd-63e2-4cb2-ab69-5c7c3c56efe8")
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stolica",
                            Price = 11999.99m,
                            Uid = new Guid("0fa7f9db-8990-4eed-bab7-3f2184b99c55")
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Televizor",
                            Price = 54999.99m,
                            Uid = new Guid("461d8e13-3f11-44f5-a678-6d86b55d6377")
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Krevet",
                            Price = 39999.99m,
                            Uid = new Guid("8046aaa7-b16f-47bd-9350-bf308c173375")
                        });
                });

            modelBuilder.Entity("Shop.Storage.Order.Order", b =>
                {
                    b.HasOne("Shop.Storage.Customer.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Shop.Storage.OrderItem.OrderItem", b =>
                {
                    b.HasOne("Shop.Storage.Order.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Storage.Product.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Storage.Customer.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shop.Storage.Order.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Shop.Storage.Product.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
